version: '3.8'

services:
  knightos-builder:
    container_name: knightos-compiler
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /root/knightos:/usr/src/knightos
    working_dir: /usr/src/knightos